### ISSUE TITLE
Sync with scroll

### ISSUE THREAD

**Issue by alexandercbooth** [MA3STR0/jquery-videosync#1]
Hi @MA3STR0,

Is it possible to use videosync to sync with a JS action, for e.g. scrolling down to a certain point on the page once the video is 10 seconds in?

Basically, I am trying to do something like the following:

```
<script>$('html,body').delay(10000).animate({scrollTop: 500});</script>
```

But with videosync instead of `.delay(10000)`.
Thanks!

**Comment by alexandercbooth** [comment]
## Update

I figured out a hacky solution in case anyone else needs it:

```
<div id="ht" class="vs animated pre-hide" data-vs-in-time=3 data-vs-in-class="fadeIn"></div>
<script>$("#ht")
.on("animationend webkitAnimationEnd oAnimationEnd MSAnimationEnd",
 function(e){
    scrolld(200);
    $(this).off(e);
 });</script>
```

Where the `scrolld` function is:

```
      <script type="text/javascript">var scrolld =  function(x) {
        $('html,body').animate({scrollTop: x});
      };</script>
```

Thanks @MA3STR0 for creating a great tool!

**Comment by MA3STR0** [comment]
Thanks for your input @alexandercbooth 
I think your hacky solution is quite ok until more people request this feature implemented natively.
